from __future__ import annotations

import argparse

from .cli_helpers import add_bulk_args, add_feedback_promote_args, add_tag_rewrite_args
from .production_pilot import (
    DEFAULT_ANSWER_QUALITY_SUITE,
    DEFAULT_PILOT_CONFIG,
    DEFAULT_PILOT_DOCS,
    DEFAULT_PILOT_SUITE,
    DEFAULT_PILOT_THRESHOLDS,
)
from .production_provider_smoke import DEFAULT_PROVIDER_SMOKE_CONFIG, DEFAULT_PROVIDER_SMOKE_QUESTION
from .production_provider_verify import DEFAULT_VERIFY_OUTPUT, DEFAULT_VERIFY_QUESTION, DEFAULT_VERIFY_WORKDIR


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="tagmemorag")
    sub = parser.add_subparsers(dest="command", required=True)

    build = sub.add_parser("build")
    build.add_argument("--docs", required=True)
    build.add_argument("--kb", default="default")
    build.add_argument("--config", default="config.yaml")

    search = sub.add_parser("search")
    search.add_argument("question")
    search.add_argument("--kb", default="default")
    search.add_argument("--top-k", type=int, default=None)
    search.add_argument("--config", default="config.yaml")
    search.add_argument("--brand", default=None)
    search.add_argument("--category", default=None)
    search.add_argument("--model", default=None)
    search.add_argument("--language", default=None)
    search.add_argument("--tag", action="append", default=[])
    search.add_argument("--debug-search", action="store_true")

    demo = sub.add_parser("demo")
    demo_sub = demo.add_subparsers(dest="demo_command", required=True)
    demo_qa = demo_sub.add_parser("qa")
    demo_qa.add_argument("question", nargs="?", default="蒸汽很小怎么办？")
    demo_qa.add_argument("--kb", default="default")
    demo_qa.add_argument("--config", default="examples/config/qa-demo.yaml")
    demo_qa.add_argument("--top-k", type=int, default=2)
    demo_qa.add_argument("--source-k", type=int, default=None)
    demo_qa.add_argument("--token-budget", type=int, default=None)
    demo_qa.add_argument("--output", default=None)
    demo_library_qa = demo_sub.add_parser("library-qa")
    demo_library_qa.add_argument("--kb", default="default")
    demo_library_qa.add_argument("--config", default="examples/config/qa-demo.yaml")
    demo_library_qa.add_argument("--manual-id", default="demo-service-manual")
    demo_library_qa.add_argument("--question", default="服务模式怎么进入？")
    demo_library_qa.add_argument("--output", default=None)
    demo_library_qa.add_argument("--no-overwrite", action="store_true")

    serve = sub.add_parser("serve")
    serve.add_argument("--host", default=None)
    serve.add_argument("--port", type=int, default=None)
    serve.add_argument("--config", default="config.yaml")

    config_cmd = sub.add_parser("config")
    config_sub = config_cmd.add_subparsers(dest="config_command", required=True)
    config_validate = config_sub.add_parser("validate")
    config_validate.add_argument("--config", default="config.yaml")
    config_validate.add_argument("--format", choices=["json"], default="json")

    langchain_cmd = sub.add_parser("langchain")
    langchain_sub = langchain_cmd.add_subparsers(dest="langchain_command", required=True)
    langchain_compare = langchain_sub.add_parser("compare")
    langchain_compare.add_argument("--file", required=True)
    langchain_compare.add_argument("--root-dir", default=None)
    langchain_compare.add_argument("--max-chars", type=int, default=500)
    langchain_compare.add_argument("--min-chars", type=int, default=50)
    langchain_compare.add_argument("--overlap-chars", type=int, default=0)

    residuals = sub.add_parser("retrain-residuals")
    residuals.add_argument("--kb", default="default")
    residuals.add_argument("--config", default="config.yaml")

    eval_parser = sub.add_parser("eval")
    eval_sub = eval_parser.add_subparsers(dest="eval_command", required=True)
    eval_run = eval_sub.add_parser("run")
    eval_run.add_argument("--suite", required=True)
    eval_run.add_argument("--docs", default=None)
    eval_run.add_argument("--config", default="config.yaml")
    eval_run.add_argument("--output", default=None)
    eval_run.add_argument("--top-k", type=int, default=None)
    eval_run.add_argument("--source-k", type=int, default=None)
    eval_run.add_argument("--steps", type=int, default=None)
    eval_run.add_argument("--decay", type=float, default=None)
    eval_run.add_argument("--amplitude-cutoff", type=float, default=None)
    eval_run.add_argument("--aggregate", choices=["max", "sum"], default=None)
    eval_run.add_argument("--metadata-field-boost", type=float, default=None)
    eval_run.add_argument("--tag-boost", type=float, default=None)
    eval_run.add_argument("--kb", default=None)
    eval_run.add_argument("--force-mode", choices=["classic", "agentic"], default=None)
    eval_run.add_argument("--reuse-built-kb", action="store_true")
    eval_run.add_argument("--eval-data-dir", default=None)
    eval_run.add_argument("--min-precision-at-k", type=float, default=None)
    eval_run.add_argument("--min-recall-at-k", type=float, default=0.8)
    eval_run.add_argument("--min-mrr", type=float, default=0.75)
    eval_run.add_argument("--min-hit-at-k", type=float, default=0.8)
    eval_run.add_argument(
        "--baseline",
        default=None,
        help="Path to baseline JSON. Suite-level thresholds are clamped to baseline - 0.02 (clipped to existing min_* values).",
    )
    eval_answer_quality = eval_sub.add_parser("answer-quality")
    eval_answer_quality.add_argument("--suite", required=True)
    eval_answer_quality.add_argument("--output", default=None)

    auth = sub.add_parser("auth")
    auth_sub = auth.add_subparsers(dest="auth_command", required=True)
    generate_key = auth_sub.add_parser("generate-key")
    generate_key.add_argument("--id", required=True)
    generate_key.add_argument("--label", default="")
    generate_key.add_argument("--scopes", default="search")
    generate_key.add_argument("--kb", default="*")
    generate_key.add_argument("--rate", type=int, default=60)
    generate_key.add_argument("--prefix", default="tmr_live_")

    manual_bulk = sub.add_parser("manual-bulk")
    manual_bulk_sub = manual_bulk.add_subparsers(dest="manual_bulk_command", required=True)
    bulk_preview = manual_bulk_sub.add_parser("preview")
    add_bulk_args(bulk_preview, include_import_args=False)
    bulk_import = manual_bulk_sub.add_parser("import")
    add_bulk_args(bulk_import, include_import_args=True)

    manualslib = sub.add_parser("manualslib")
    manualslib_sub = manualslib.add_subparsers(dest="manualslib_command", required=True)
    manualslib_import = manualslib_sub.add_parser("import-url")
    manualslib_import.add_argument("--url", required=True)
    manualslib_import.add_argument("--output-dir", required=True)
    manualslib_import.add_argument("--max-pages", type=int, default=None)
    manualslib_import.add_argument("--timeout-seconds", type=float, default=20.0)
    manualslib_opencli = manualslib_sub.add_parser("import-opencli")
    manualslib_opencli.add_argument("--brand", default="hisense")
    manualslib_opencli.add_argument("--category", default=None)
    manualslib_opencli.add_argument("--limit", type=int, default=20)
    manualslib_opencli.add_argument("--output-dir", default=None)
    manualslib_opencli.add_argument("--max-pages", type=int, default=None)
    manualslib_opencli.add_argument("--timeout-seconds", type=float, default=20.0)
    manualslib_opencli.add_argument("--preview", action="store_true")

    knowledge = sub.add_parser("knowledge")
    knowledge_sub = knowledge.add_subparsers(dest="knowledge_command", required=True)
    sample_web = knowledge_sub.add_parser("sample-web")
    sample_web.add_argument("--url", action="append", required=True)
    sample_web.add_argument("--output-dir", default=None)
    sample_web.add_argument("--kb", default="default")
    sample_web.add_argument("--domain", default="public_web")
    sample_web.add_argument("--doc-type", default="web_page")
    sample_web.add_argument("--tag", action="append", default=[])
    sample_web.add_argument("--timeout-seconds", type=float, default=20.0)
    sample_web.add_argument("--preview", action="store_true")

    manual_library = sub.add_parser("manual-library")
    manual_library_sub = manual_library.add_subparsers(dest="manual_library_command", required=True)
    library_rebuild = manual_library_sub.add_parser("rebuild")
    library_rebuild.add_argument("--kb", default="default")
    library_rebuild.add_argument("--config", default="config.yaml")
    library_rebuild.add_argument("--mode", choices=["full", "incremental", "auto"], default="full")
    library_rebuild.add_argument("--no-fallback", action="store_true")
    library_rebuild.add_argument("--queued", action="store_true")
    library_jobs = manual_library_sub.add_parser("rebuild-jobs")
    library_jobs_sub = library_jobs.add_subparsers(dest="manual_library_jobs_command", required=True)
    jobs_list = library_jobs_sub.add_parser("list")
    jobs_list.add_argument("--kb", default=None)
    jobs_list.add_argument("--config", default="config.yaml")
    jobs_list.add_argument("--status", default=None)
    jobs_inspect = library_jobs_sub.add_parser("inspect")
    jobs_inspect.add_argument("--config", default="config.yaml")
    jobs_inspect.add_argument("--job-id", required=True)
    jobs_cancel = library_jobs_sub.add_parser("cancel")
    jobs_cancel.add_argument("--config", default="config.yaml")
    jobs_cancel.add_argument("--job-id", required=True)
    library_dirty = manual_library_sub.add_parser("dirty")
    library_dirty.add_argument("--kb", default="default")
    library_dirty.add_argument("--config", default="config.yaml")
    library_dirty.add_argument("--format", choices=["json", "csv"], default="json")
    library_registry = manual_library_sub.add_parser("registry")
    library_registry_sub = library_registry.add_subparsers(dest="manual_registry_command", required=True)
    registry_inspect_parser = library_registry_sub.add_parser("inspect")
    registry_inspect_parser.add_argument("--kb", default="default")
    registry_inspect_parser.add_argument("--config", default="config.yaml")
    registry_migrate = library_registry_sub.add_parser("migrate")
    registry_migrate.add_argument("--kb", default="default")
    registry_migrate.add_argument("--config", default="config.yaml")
    registry_migrate.add_argument("--dry-run", action="store_true", default=False)
    registry_verify = library_registry_sub.add_parser("verify-blobs")
    registry_verify.add_argument("--kb", default="default")
    registry_verify.add_argument("--config", default="config.yaml")
    library_bundle = manual_library_sub.add_parser("bundle")
    library_bundle_sub = library_bundle.add_subparsers(dest="manual_bundle_command", required=True)
    bundle_export = library_bundle_sub.add_parser("export")
    bundle_export.add_argument("--kb", default="default")
    bundle_export.add_argument("--config", default="config.yaml")
    bundle_export.add_argument("--output", required=True)
    bundle_inspect = library_bundle_sub.add_parser("inspect")
    bundle_inspect.add_argument("--bundle", required=True)
    bundle_inspect.add_argument("--config", default=None)
    bundle_inspect.add_argument("--target-kb", default=None)
    bundle_inspect.add_argument("--conflict-mode", choices=["fail", "skip", "overwrite"], default="fail")
    bundle_import = library_bundle_sub.add_parser("import")
    bundle_import.add_argument("--bundle", required=True)
    bundle_import.add_argument("--config", default="config.yaml")
    bundle_import.add_argument("--target-kb", default=None)
    bundle_import.add_argument("--conflict-mode", choices=["fail", "skip", "overwrite"], default="fail")
    bundle_import.add_argument("--dry-run", action="store_true", default=False)

    tag = sub.add_parser("tag")
    tag_sub = tag.add_subparsers(dest="tag_command", required=True)
    tag_stats = tag_sub.add_parser("stats")
    tag_stats.add_argument("--kb", default="default")
    tag_stats.add_argument("--config", default="config.yaml")
    tag_policy = tag_sub.add_parser("policy")
    tag_policy.add_argument("--kb", default="default")
    tag_policy.add_argument("--config", default="config.yaml")
    tag_policy.add_argument("--file", default=None, help="Write policy from JSON file; omit to print current policy.")
    tag_preview = tag_sub.add_parser("rewrite-preview")
    add_tag_rewrite_args(tag_preview, include_commit_args=False)
    tag_commit = tag_sub.add_parser("rewrite")
    add_tag_rewrite_args(tag_commit, include_commit_args=True)

    qdrant = sub.add_parser("qdrant")
    qdrant_sub = qdrant.add_subparsers(dest="qdrant_command", required=True)
    qdrant_inspect = qdrant_sub.add_parser("inspect")
    qdrant_inspect.add_argument("--kb", default="default")
    qdrant_inspect.add_argument("--config", default="config.yaml")

    provider = sub.add_parser("provider")
    provider_sub = provider.add_subparsers(dest="provider_command", required=True)
    provider_probe = provider_sub.add_parser("probe")
    provider_probe.add_argument("--config", default="config.yaml")
    provider_probe.add_argument("--kb", default="default")
    provider_probe.add_argument("--format", choices=["json"], default="json")
    provider_probe.add_argument("--all", action="store_true", default=False)
    provider_probe.add_argument("--embedding", action="store_true", default=False)
    provider_probe.add_argument("--answer", action="store_true", default=False)
    provider_probe.add_argument("--reranker", action="store_true", default=False)
    provider_probe.add_argument("--qdrant", action="store_true", default=False)
    provider_probe.add_argument("--s3", action="store_true", default=False)

    production_provider = sub.add_parser("production-provider")
    production_provider_sub = production_provider.add_subparsers(dest="production_provider_command", required=True)
    production_provider_smoke = production_provider_sub.add_parser("smoke")
    production_provider_smoke.add_argument("--config", default=DEFAULT_PROVIDER_SMOKE_CONFIG)
    production_provider_smoke.add_argument("--kb", default="default")
    production_provider_smoke.add_argument("--manual", action="append", default=[], help="Manual source document path. Repeat for many files.")
    production_provider_smoke.add_argument("--metadata", default=None, help="Optional JSON, JSONL, or CSV metadata path. Omit to use *.metadata.json sidecars.")
    production_provider_smoke.add_argument("--metadata-format", choices=["json", "jsonl", "csv"], default="json")
    production_provider_smoke.add_argument("--workdir", default=None)
    production_provider_smoke.add_argument("--output", default=None)
    production_provider_smoke.add_argument("--format", choices=["json", "markdown"], default="json")
    production_provider_smoke.add_argument("--question", default=DEFAULT_PROVIDER_SMOKE_QUESTION)
    production_provider_smoke.add_argument("--rebuild-mode", choices=["full", "incremental", "auto"], default="full")
    production_provider_smoke.add_argument("--answer-top-k", type=int, default=6)
    production_provider_smoke.add_argument("--answer-source-k", type=int, default=6)
    production_provider_smoke.add_argument("--reset-qdrant-collection", action="store_true", default=False)
    production_provider_verify = production_provider_sub.add_parser("verify")
    production_provider_verify.add_argument("--level", choices=["smoke", "pilot"], default="smoke")
    production_provider_verify.add_argument("--config", default=DEFAULT_PROVIDER_SMOKE_CONFIG)
    production_provider_verify.add_argument("--kb", default="default")
    production_provider_verify.add_argument("--manual", action="append", default=[], help="Manual source document path. Repeat for many files.")
    production_provider_verify.add_argument("--metadata", default=None)
    production_provider_verify.add_argument("--metadata-format", choices=["json", "jsonl", "csv"], default="json")
    production_provider_verify.add_argument("--workdir", default=DEFAULT_VERIFY_WORKDIR)
    production_provider_verify.add_argument("--output", default=DEFAULT_VERIFY_OUTPUT)
    production_provider_verify.add_argument("--format", choices=["json", "markdown"], default="json")
    production_provider_verify.add_argument("--verify-output", default=None)
    production_provider_verify.add_argument("--verify-format", choices=["json", "markdown"], default="json")
    production_provider_verify.add_argument("--question", default=DEFAULT_VERIFY_QUESTION)
    production_provider_verify.add_argument("--skip-docker", action="store_true", default=False)
    production_provider_verify.add_argument("--skip-bucket", action="store_true", default=False)
    production_provider_verify.add_argument("--no-reset-qdrant", action="store_true", default=False)
    production_provider_verify.add_argument("--check-only", action="store_true", default=False)
    production_provider_verify.add_argument("--pilot-suite", default=DEFAULT_PILOT_SUITE)
    production_provider_verify.add_argument("--pilot-docs", default=DEFAULT_PILOT_DOCS)
    production_provider_verify.add_argument("--pilot-workdir", default=None)
    production_provider_verify.add_argument("--pilot-output", default=None)
    production_provider_verify.add_argument("--pilot-format", choices=["json", "markdown"], default="json")
    production_provider_verify.add_argument("--pilot-top-k", type=int, default=None)
    production_provider_verify.add_argument("--pilot-source-k", type=int, default=None)
    production_provider_verify.add_argument("--pilot-min-recall-at-k", type=float, default=DEFAULT_PILOT_THRESHOLDS.min_recall_at_k)
    production_provider_verify.add_argument("--pilot-min-mrr", type=float, default=DEFAULT_PILOT_THRESHOLDS.min_mrr)
    production_provider_verify.add_argument("--pilot-min-hit-at-k", type=float, default=DEFAULT_PILOT_THRESHOLDS.min_hit_at_k)
    production_provider_verify.add_argument("--pilot-hashing-baseline", default=None)
    production_provider_verify.add_argument("--pilot-production-baseline", default=None)
    production_provider_verify.add_argument("--pilot-informational-suites", default="")
    production_provider_verify.add_argument("--pilot-accepted-suites", default="")

    readiness = sub.add_parser("readiness")
    readiness_sub = readiness.add_subparsers(dest="readiness_command", required=True)
    readiness_smoke = readiness_sub.add_parser("smoke")
    readiness_smoke.add_argument("--workdir", default=None)
    readiness_smoke.add_argument("--keep-workdir", action="store_true", default=False)

    pilot = sub.add_parser("pilot")
    pilot_sub = pilot.add_subparsers(dest="pilot_command", required=True)
    pilot_run = pilot_sub.add_parser("run")
    pilot_run.add_argument("--config", default=DEFAULT_PILOT_CONFIG)
    pilot_run.add_argument("--suite", default=DEFAULT_PILOT_SUITE)
    pilot_run.add_argument("--docs", default=DEFAULT_PILOT_DOCS)
    pilot_run.add_argument("--workdir", default=None)
    pilot_run.add_argument("--output", default=None)
    pilot_run.add_argument("--format", choices=["json", "markdown"], default="json")
    pilot_run.add_argument("--top-k", type=int, default=None)
    pilot_run.add_argument("--source-k", type=int, default=None)
    pilot_run.add_argument("--min-recall-at-k", type=float, default=DEFAULT_PILOT_THRESHOLDS.min_recall_at_k)
    pilot_run.add_argument("--min-mrr", type=float, default=DEFAULT_PILOT_THRESHOLDS.min_mrr)
    pilot_run.add_argument("--min-hit-at-k", type=float, default=DEFAULT_PILOT_THRESHOLDS.min_hit_at_k)
    pilot_run.add_argument("--hashing-baseline", default=None)
    pilot_run.add_argument("--production-baseline", default=None)
    pilot_run.add_argument("--answer-quality-suite", default=DEFAULT_ANSWER_QUALITY_SUITE)
    pilot_run.add_argument("--skip-answer-quality", action="store_true", default=False)
    pilot_run.add_argument(
        "--informational-suites",
        default="",
        help="Comma-separated eval suite filenames whose diagnosis is informational and not blocking.",
    )
    pilot_run.add_argument(
        "--accepted-suites",
        default="",
        help="Comma-separated eval suite filenames whose diagnosis has been reviewed and accepted as non-blocking.",
    )

    epa = sub.add_parser("epa")
    epa_sub = epa.add_subparsers(dest="epa_command", required=True)
    epa_rebuild = epa_sub.add_parser("rebuild")
    epa_rebuild.add_argument("--config", default="config.yaml")
    epa_rebuild.add_argument("--force", action="store_true")

    feedback = sub.add_parser("feedback")
    feedback_sub = feedback.add_subparsers(dest="feedback_command", required=True)
    feedback_submit = feedback_sub.add_parser("submit")
    feedback_submit.add_argument("--kb", default="default")
    feedback_submit.add_argument("--config", default="config.yaml")
    feedback_submit.add_argument("--json", required=True, help="Feedback payload JSON file.")
    feedback_list = feedback_sub.add_parser("list")
    feedback_list.add_argument("--kb", default="default")
    feedback_list.add_argument("--config", default="config.yaml")
    feedback_list.add_argument("--status", default=None)
    feedback_list.add_argument("--outcome", default=None)
    feedback_list.add_argument("--query", default=None)
    feedback_list.add_argument("--limit", type=int, default=50)
    feedback_review = feedback_sub.add_parser("review")
    feedback_review.add_argument("--kb", default="default")
    feedback_review.add_argument("--config", default="config.yaml")
    feedback_review.add_argument("--feedback-id", required=True)
    feedback_review.add_argument("--status", default=None)
    feedback_review.add_argument("--operator-note", default=None)
    feedback_preview = feedback_sub.add_parser("promote-preview")
    add_feedback_promote_args(feedback_preview)
    feedback_promote = feedback_sub.add_parser("promote")
    add_feedback_promote_args(feedback_promote)
    feedback_promote.add_argument("--append", action="store_true")
    feedback_promote.add_argument("--overwrite", action="store_true")


    return parser
