"""Ingest real product manuals: classify, move into category subdirs, write sidecars.

Scans `product_manuals/*.pdf` (or `*.md` / `*.txt`) at the root level, infers
each manual's `product_category` / `brand` / `product_model` from the filename
(with PDF first-page text as fallback), then:

  1. Moves the source file to `product_manuals/<category>/<filename>` (the
     canonical layout per `product_manuals/README.md`).
  2. Writes a sidecar `<filename>.metadata.json` next to it, populated with
     best-guess fields. The user reviews and corrects before running
     `python -m tagmemorag build`.

Idempotent: files already inside a recognized category subdir are left alone.

Usage:
  python scripts/ingest_real_manuals.py [--root product_manuals]
                                        [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from pypdf import PdfReader  # noqa: E402

DEFAULT_ROOT = REPO_ROOT / "product_manuals"

# Filename → category mapping (case-insensitive). Order matters: most specific first.
FILENAME_PATTERNS: list[tuple[re.Pattern, dict]] = [
    (re.compile(r"^ASKO\s*W\d", re.I), {"brand": "ASKO", "product_category": "washer"}),
    (re.compile(r"^HISENSE\s*HR", re.I), {"brand": "Hisense", "product_category": "refrigerator"}),
    # Hisense DH = Dryer (DHGA / DHQE 系列均为干衣机)
    (re.compile(r"^HISENSE\s*DH", re.I), {"brand": "Hisense", "product_category": "dryer"}),
    # Hisense BSA = Built-in oven (烤箱)
    (re.compile(r"^HISENSE\s*BSA", re.I), {"brand": "Hisense", "product_category": "oven"}),
]

# Free-text keyword fallback (apply to first ~1000 chars of PDF page 0).
KEYWORD_CATEGORIES: list[tuple[re.Pattern, str]] = [
    (re.compile(r"洗碗机|洗碗機|dishwasher", re.I), "dishwasher"),
    (re.compile(r"烤箱|oven|cooking\s*system", re.I), "oven"),
    (re.compile(r"干衣机|乾衣機|dryer|laundry\s*not\s*dried|drying\s*program", re.I), "dryer"),
    (re.compile(r"洗衣机|洗衣機|washer|washing\s*machine", re.I), "washer"),
    (re.compile(r"冰箱|冷藏|refrigerator|fridge", re.I), "refrigerator"),
    (re.compile(r"空调|空調|air\s*conditioner|aircon", re.I), "air_conditioner"),
    (re.compile(r"咖啡机|咖啡機|coffee\s*machine", re.I), "coffee"),
]

KNOWN_CATEGORIES = {"washer", "dishwasher", "refrigerator", "air_conditioner", "coffee", "oven", "dryer"}


def _model_from_filename(filename: str) -> str | None:
    """Extract a probable model code from filename. e.g. 'HISENSE HR6FDFF701SW' → 'HR6FDFF701SW'."""
    stem = Path(filename).stem
    parts = stem.split()
    if len(parts) >= 2:
        return parts[-1]
    return stem or None


def _classify_by_filename(filename: str) -> dict | None:
    for pat, info in FILENAME_PATTERNS:
        if pat.search(filename):
            return dict(info)
    return None


def _classify_by_pdf_first_page(pdf_path: Path) -> str | None:
    try:
        reader = PdfReader(str(pdf_path))
        if not reader.pages:
            return None
        text = (reader.pages[0].extract_text() or "")[:1500]
    except Exception as exc:
        print(f"[warn] could not read first page of {pdf_path}: {exc}", file=sys.stderr)
        return None
    for pat, category in KEYWORD_CATEGORIES:
        if pat.search(text):
            return category
    return None


def _build_sidecar(
    *,
    source_file: str,
    brand: str | None,
    category: str,
    model: str | None,
    language: str = "zh-CN",
) -> dict:
    brand_slug = (brand or "unknown").lower().replace(" ", "-")
    model_slug = (model or Path(source_file).stem).lower().replace(" ", "-")
    return {
        "manual_id": f"{brand_slug}-{model_slug}-{language.lower()}-v1",
        "title": Path(source_file).stem,
        "source_file": source_file,
        "brand": brand or "unknown",
        "product_category": category,
        "product_name": model or "",
        "product_model": model or "",
        "language": language,
        "version": "v1",
        "tags": [category],
        "status": "active",
        "uploaded_at": date.today().isoformat(),
        "checksum": "",
        "notes": "auto-generated by scripts/ingest_real_manuals.py; user may correct",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    if not args.root.is_dir():
        print(f"error: {args.root} is not a directory", file=sys.stderr)
        return 2

    moved = 0
    sidecars_written = 0
    skipped = 0
    unresolved: list[Path] = []

    for entry in sorted(args.root.iterdir()):
        if not entry.is_file():
            continue
        if entry.suffix.lower() not in {".pdf", ".md", ".txt"}:
            continue
        if entry.name.upper() == "README.MD":
            continue

        # Classify
        info = _classify_by_filename(entry.name) or {}
        category = info.get("product_category")
        if not category and entry.suffix.lower() == ".pdf":
            category = _classify_by_pdf_first_page(entry)
        if not category:
            unresolved.append(entry)
            continue
        if category not in KNOWN_CATEGORIES:
            print(f"[warn] {entry.name}: unknown category {category!r}, skipping", file=sys.stderr)
            unresolved.append(entry)
            continue

        # Plan move
        target_dir = args.root / category
        target_pdf = target_dir / entry.name
        sidecar_path = target_pdf.with_suffix(target_pdf.suffix + ".metadata.json")
        # OS-aware: sidecar should be `<basename>.metadata.json` not `<file>.pdf.metadata.json`.
        # Actually project README example shows `fridge_gorenje.metadata.json` next to
        # `fridge_gorenje.pdf` — i.e. replace suffix, not append.
        sidecar_path = target_dir / (entry.stem + ".metadata.json")

        action = "DRY-RUN" if args.dry_run else "MOVE"
        print(f"[{action}] {entry.name} → {target_pdf.relative_to(args.root)}")

        if args.dry_run:
            skipped += 1
            continue

        target_dir.mkdir(parents=True, exist_ok=True)
        if target_pdf.exists():
            print(f"  [skip-move] {target_pdf.name} already exists in target dir", file=sys.stderr)
        else:
            entry.rename(target_pdf)
            moved += 1

        # Sidecar (write only if missing — allow user-edited sidecars to survive re-runs)
        if not sidecar_path.exists():
            model = _model_from_filename(entry.name)
            sidecar = _build_sidecar(
                source_file=entry.name,
                brand=info.get("brand"),
                category=category,
                model=model,
            )
            sidecar_path.write_text(json.dumps(sidecar, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            sidecars_written += 1
            print(f"  [sidecar] wrote {sidecar_path.relative_to(args.root)}")
        else:
            print(f"  [sidecar] {sidecar_path.name} already exists, leaving as-is")

    print(f"\nSummary: moved={moved} sidecars_written={sidecars_written} skipped={skipped}")
    if unresolved:
        print("Unresolved (could not classify; please move + write sidecar manually):", file=sys.stderr)
        for p in unresolved:
            print(f"  - {p.name}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
